Controllers/ApplicationTypeController.cs
using Beml.ECommerce.App.Data;
using Beml.ECommerce.App.Models;
using Microsoft.AspNetCore.Mvc;

namespace Beml.ECommerce.App.Controllers
{
    public class ApplicationTypeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ApplicationTypeController(ApplicationDbContext db) {
            _db = db;
        }

        //Get-Index
        public IActionResult Index()
        {
            IEnumerable<ApplicationType> objList= _db.ApplicationTypes;
            return View(objList);
        }

        #region "CREATE"
        //Get-Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Get-Create
        public IActionResult Create(ApplicationType objApplicationType)
        {
            if (ModelState.IsValid)
            {
                _db.ApplicationTypes.Add(objApplicationType);
                _db.SaveChanges();
                TempData["success"] = "Created Application Type Successfully!!";
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion

        #region "Update"
        //GET-Update

        public IActionResult Update(int id)
        {

            if (id == 0)
            {
                return NotFound();
            }
            ApplicationType objApplication = _db.ApplicationTypes.First<ApplicationType>(ele => ele.ApplicationId == id);
            if (objApplication == null)
            {
                return NotFound();
            }
            return View(objApplication);                  
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ApplicationType obj)
        {
            if (ModelState.IsValid)
            {
                _db.ApplicationTypes.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Updated Application Type Successfully!!";
                return RedirectToAction("Index");

            }
            return View();
        }
        #endregion

        #region "Delete"
        //GET-Update

        public IActionResult Delete(int id)
        {

            if (id == 0)
            {
                return NotFound();
            }
            ApplicationType objApplication = _db.ApplicationTypes.First<ApplicationType>(ele => ele.ApplicationId == id);
            if (objApplication == null)
            {
                return NotFound();
            }
            return View(objApplication);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(ApplicationType obj)
        {
            if (ModelState.IsValid)
            {
                _db.ApplicationTypes.Remove(obj);
                _db.SaveChanges();
                TempData["success"] = "Deleted Application Type Successfully!!";
                return RedirectToAction("Index");   

            }
            return View();
        }
        #endregion

    }
}

Controllers/CategoryController.cs
using Beml.ECommerce.App.Data;
using Beml.ECommerce.App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.Linq.Expressions;

namespace Beml.ECommerce.App.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objList = _db.Categories;
            return View(objList);
        }
        //CREATE-GET
        public IActionResult Create()
        {
            return View();
        }
        //CREATE-POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if(ModelState.IsValid)
            {
                _db.Categories.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Created Category Successfully!!";
                return RedirectToAction("Index");
            }
            return View();
        }

        // UPDATE  GET
        public IActionResult Update(int id)
        {
            if(id==0)
            {
                return NotFound();
            }
            Category objCategory = _db.Categories.First<Category>(ele => ele.CategoryId == id);
            if (objCategory == null) {
                return NotFound();
            }
            return View(objCategory);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Category objCategory)
        {
            if (ModelState.IsValid)
            {
                _db.Categories.Update(objCategory);
                _db.SaveChanges();
                TempData["success"] = "Updated Category Successfully!!";
                return RedirectToAction("Index");
            }
            
            return View();
        }

        //DELETE GET
        public IActionResult Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            Category objCategory = _db.Categories.First<Category>(ele => ele.CategoryId == id);
            if (objCategory == null)
            {
                return NotFound();
            }
            return View(objCategory);
           
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCategory(Category objCat)
        {
            var objCategoryDel = _db.Categories.Find(objCat.CategoryId);
            if (objCategoryDel == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Categories.Remove(objCategoryDel);
                _db.SaveChanges();
                TempData["success"] = "Deleted Category Successfully!!";
                return RedirectToAction("Index");
            }    
            return View();
        }
    }
}

Controllers/ProductController.cs
using Beml.ECommerce.App.Data;
using Beml.ECommerce.App.Models;
using Beml.ECommerce.App.Models.VM;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System;
using System.ComponentModel;
using System.Linq.Expressions;

namespace Beml.ECommerce.App.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        //Below Variable is used to access the Images folders which is inside the wwwroot
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }
        //ProductList - GET
        public IActionResult IndexOld()
        {
            IEnumerable<Product> objList = _db.Products;

            foreach(var obj in objList)
            {
                obj.Category = _db.Categories.FirstOrDefault(u =>u.CategoryId == obj.CategoryId);
            }
            return View(objList);
        }

        public IActionResult Index()
        {
            IEnumerable<Product> objList = _db.Products.Include(i=>i.Category).Include(ele=>ele.ApplicationType);           
            return View(objList);
        }
        //CREATE-GET
        /*
        public IActionResult UpsertVBOrVD(int? id)
        {
            //1 way to display the dropdownlist in view is selectListItem(Microsoft.AspNet.Core.Mvc.Rendering)
            // U can pass the data of dropdownlist using ViewBag or ViewData C->V

            //Ideally ViewBag or ViewData its not a recommended solution for using the dropdown field as 
            //It is advisable that your view should be strongly typed but when we use ViewData/ViewBag it breaks that.

            IEnumerable<SelectListItem> objCategoyList = _db.Categories.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.CategoryId.ToString()
            });
            //ViewBag.CategoryDropDown = objCategoyList;

            ViewData["CategoryDropDown"] = objCategoyList;

            Product objProd = new Product();
            if (id == null)
            {
                //Create
                return View();
            }
            else
            {
                objProd = _db.Products.First(el => el.ProductId == id);
                return View(objProd);
            }

        }
        */


        public IActionResult Upsert(int? id)
        {
            ProductVM objProductVM = new ProductVM()
            {
                Product = new Product(),
                CategoryListItem = _db.Categories.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.CategoryId.ToString()
                }),
                ApplicationListItem= _db.ApplicationTypes.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.ApplicationId.ToString()
                })
            };
                        
            if (id == null)
            {
                return View(objProductVM);
            }
            else
            {
                objProductVM.Product = _db.Products.First(el => el.ProductId == id);
                return View(objProductVM);
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM objVM)
        {
                  //Fetch Image
                var files = HttpContext.Request.Form.Files;
                //Important
                string webRootPath = _webHostEnvironment.WebRootPath;

                if (objVM.Product.ProductId == 0)
                {
                    //Create
                    string upload = webRootPath + WC.ImagePath;
                    string fileName = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(files[0].FileName);
                    objVM.Product.ShortDesc = objVM.Product.Description.Substring(0,12);
                //copy to the location
                using (var filestream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(filestream);
                    }
                    objVM.Product.ImagePath = fileName + extension;

                    _db.Products.Add(objVM.Product);
                TempData["success"] = "Created Product Successfully!!";

            }
                else
                {
                //Update
                var objFromDb = _db.Products.AsNoTracking().FirstOrDefault(u => u.ProductId == objVM.Product.ProductId);
                //Remove the existing file and create the new file
                if (files.Count > 0)
                {
                    string upload = webRootPath + WC.ImagePath;
                    string fileName = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(files[0].FileName);
                    objVM.Product.ShortDesc = objVM.Product.Description.Substring(0, 15);
                    var oldFile = Path.Combine(upload, objFromDb.ImagePath);

                    if (System.IO.File.Exists(oldFile))
                    {
                        System.IO.File.Delete(oldFile);
                    }

                    using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    objVM.Product.ShortDesc = objVM.Product.Description.Substring(0, 12);
                    objVM.Product.ImagePath = fileName + extension;
                }
                else
                {
                    objVM.Product.ImagePath = objFromDb.ImagePath;
                }
                _db.Products.Update(objVM.Product);
                TempData["success"] = "Updated Product Successfully!!";
            }
                _db.SaveChanges();
                return RedirectToAction("Index");
          
        }


        #region "Delete"

        public IActionResult Delete(int? Id)
        {
            if (Id == 0)
            {
                return NotFound();
            }

            Product objProduct = _db.Products.Include(i => i.Category).First(el => el.ProductId == Id);
            if (objProduct == null)
            {
                return NotFound();
            }
            return View(objProduct);
        
        }
        #endregion
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProduct(int? ProductId)
        {
            var obj = _db.Products.Find(ProductId);
            if (obj == null)
            {
                return NotFound();
            }

            string upload = _webHostEnvironment.WebRootPath + WC.ImagePath;
            var oldFile = Path.Combine(upload, obj.ImagePath);

            if (System.IO.File.Exists(oldFile))
            {
                System.IO.File.Delete(oldFile);
            }


            _db.Products.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Deleted Product Successfully!!";
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_IndividualProductCard.cshtml
@model Beml.ECommerce.App.Models.Product       
 
<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ','_')">
            <!-- Card-->
            <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
                <div class="card-body px-3 pt-3 pb-1 row">
                    <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@Model.Price</span> / Inr</label> </div>
                </div>
                <img class="card-img-top img-fluid d-block mx-auto mb-3" style="width:300px; height:300px;object-fit:scale-down;" src="@WC.ImagePath@Model.ImagePath" alt="Card image cap">
                <div class="card-body p-1 px-3 row">
                    <div class="col-6">
                <span class="badge p-2 border w-100" style="background-color:lavenderblush; color:ButtonText">@Model.Category.Name</span>
                    </div>
                <div class="col-6 border-0">
                <span class="badge p-2 border w-100" style="background-color:aliceblue; color:ButtonText">@Model.ApplicationType.Name</span>
                </div>
                <div class="col-12 pt-2" style="font-size:13px; text-align:justify" >
                <p> @Html.Raw(Model.ShortDesc)</p>
                </div>
                <div class="col-12 p-1">
                    <a asp-action="Details" asp-route-id="@Model.ProductId" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
                </div>
                </div>
            </div>
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using Beml.ECommerce.App.Utility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Beml.ECommerce.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/Beml.ECommerce.App.styles.css" asp-append-version="true" />

    @*Adding ToastrJs Step1*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />   

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Beml.ECommerce.App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu">
                                <li> <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Type</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a></li>
                                <li><hr class="dropdown-divider"></li>
                                
                            </ul>
                        </li>

                        @*Shopping Cart Start*@
                        <li>
                            @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart)!=null){
                                <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                    @{
                                          var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart).Count;

                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                                }
                            else{
                            <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                        <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                            </a>
                            }
                        </li>
                        @*Shopping Cart End*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Beml.ECommerce.App - <a asp-area="" asp-controller="Home" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>    
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
        @*<h3 class="text-info">@TempData["success"]</h3>*@

        <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
        toastr.success('@TempData["success"]')
        </script>
        
}
@if (TempData["error"] != null)
{
   @* <h3 class="text-danger">@TempData["error"]</h3>*@

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["success"]')
    </script>
}